### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 0usssama** [VoldemortCommunity/ComboGen#1]
```
SyntaxError: Non-ASCII character '\xfa' in file combogen on line 7, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by voldemort1912** [comment]
Are you Using Termux or Linux? This Program was focused only on Android Termux Users.

**Comment by 0usssama** [comment]
Linux user

**Comment by voldemort1912** [comment]
This program uses Termux Specific Commands, i can create a seperate version for Linux Users in a while.
