### ISSUE TITLE
lxml problem 

### ISSUE THREAD

**Issue by PinkWards** [VoldemortCommunity/ComboGen#10]
I execute the program and i stuck in lxml part, need help!!

**Comment by lilcanopener1** [comment]
Wait lxml can take up to 20 mins out your phone down and wait

**Comment by PinkWards** [comment]
hmm.. okay I'll try again, thank you for response!

**Comment by lilcanopener1** [comment]
No problem got anything you need help with? HMU on discord reggie#9225

**Comment by PinkWards** [comment]
Thank youu! It works finally! Keep safe and thankyouu again!!
