### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Emon526** [VoldemortCommunity/ComboGen#11]
File "/data/data.com.termux/files/home/combogen/
combogen", line 6
Z
^
SyntaxError : invalid syntax

what is the problem?

**Comment by sssxhhxhh** [comment]
Same problem

**Comment by sssxhhxhh** [comment]
![Uploading Screenshot_2020-10-13-00-51-33-052_com.termux.jpg…]()

**Comment by artemiszuk** [comment]
same problem

**Comment by lilcanopener1** [comment]
hey calm down wait a few months the problem will be resolved

**Comment by mohammedas14** [comment]
Same problem

**Comment by sai-kumar222** [comment]
Same problem

**Comment by fardindiwan** [comment]
Same problem

**Comment by lilcanopener1** [comment]
Guys this problem is derived from not putting a : or putting == when there
supposed to be a = it shouldn't be long until the problem is fixed things
like this programmers like me can see within 5 to 10 mins depending on how
large the code is. Thanks for reading have a good day.

**Comment by ALT-F4-XD** [comment]
Same

**Comment by asudoy** [comment]
Same problem

**Comment by lilcanopener1** [comment]
Just do python3 combogen that should fix it :)

**Comment by assanegaye** [comment]
How to solve syntax error line 6 please

**Comment by voldemort1912** [comment]
Solved. Please update to the latest version.
