### ISSUE TITLE
Syntax problem

### ISSUE THREAD

**Issue by asudoy** [VoldemortCommunity/ComboGen#12]
When I type python combogen  then it File "/data/data/com.termux/files/home/ComboGen/combogen", line 6
    Z.

     ^
SyntaxError: invalid 

> 
But python is installed

> `syntax[https://pasteboard.co/JzKrr4S.png](https://pasteboard.co/JzKrr4S.png) `

**Comment by lilcanopener1** [comment]
Guys just do python3 combogeb

**Comment by Raven-312** [comment]
Syntaxis error

**Comment by voldemort1912** [comment]
Solved. Please verify.
