### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by TestingGithuv** [VoldemortCommunity/ComboGen#17]
How do i get a login 

 > Authorization Required. Please Verify Your Credentials.
 > Username : bugle
 > Password : 
 > Authorization Unsuccessful. Program Terminated.
 > Combos Collected : 0

**Comment by voldemort1912** [comment]
Voldemort's Newsletter, [1/3/21, 3:00 AM]
ComboGen has been Updated to v4.0 all thanks to @Nube46's Donation. It's no longer free to use and has an authentication system as per his request. Anybody willing to purchase a subscription can do so for 5$.

Github : https://github.com/VoldemortCommunity/ComboGen

In Addition to the Current Mechanism, another algorithm will be implemented soon allowing users to send upto 600 requests per month for free. After which paid subscriptions can be purchased as per their desire. This program will be available soon under a different name. To protect the integrity and assure a long service, limited one time authentication tokens will be handed out that register a device. PM me [@hewhomustn0tbenamed](https://t.me/hewhomustn0tbenamed) to reserve yours.
