### ISSUE TITLE
DuckDuckGo

### ISSUE THREAD

**Issue by lilcanopener1** [VoldemortCommunity/ComboGen#6]
The DuckDuckGo scrapping doesn't work  guessing it's the algorithm bc I did site:paste in.com "keywords here" and it gave me a error and when I am scrapping with DuckDuckGo it will quickly go to the next keywords with 0 urls 

PS. Thx for reading thru  I did

**Comment by voldemort1912** [comment]
you do not need to provide the "site:pastebin.com" search filter, the program had implemented it by-default. Please only provide keywords without using the quotes.

**Comment by lilcanopener1** [comment]
No I do not add that I'm saying no links come back from DuckDuckGo I think you added it wrong try

site:pastebin.com 

Thx

**Comment by voldemort1912** [comment]
> No I do not add that I'm saying no links come back from DuckDuckGo I think you added it wrong try
> 
> site:pastebin.com 
> 
> Thx

![Screenshot_20200825-235026.jpg](https://user-images.githubusercontent.com/47709143/91212410-cb628f00-e72d-11ea-96ee-325aaea531e2.jpg)

I don't think there are any mistakes in the source. Please ensure that your IP address is live on DuckDuckGo. I will look into the matter to see if there's any other factors that might have caused your problem.
