### ISSUE TITLE
error

### ISSUE THREAD

**Issue by KoolSkins** [VoldemortCommunity/ComboGen#7]
![Screenshot_20200824-180449_Termux.jpg](https://user-images.githubusercontent.com/70181124/91111253-e6050d00-e634-11ea-9308-94279f82cabc.jpg)

**Comment by sqlasskicker** [comment]
Pprint error

**Comment by lilcanopener1** [comment]
Pip install pprint -y

**Comment by lilcanopener1** [comment]
Nvm try 
pip install prettyprint

**Comment by sqlasskicker** [comment]
Try pip install prettyprinter

**Comment by voldemort1912** [comment]
> ![Screenshot_20200824-180449_Termux.jpg](https://user-images.githubusercontent.com/70181124/91111253-e6050d00-e634-11ea-9308-94279f82cabc.jpg)

Recent python updates removed the pprint module from the pip repository as it masked the python standard PrettyPrint functions, I'll fix it in a short while.

**Comment by voldemort1912** [comment]
> Try pip install prettyprinter

> Pprint error

> ![Screenshot_20200824-180449_Termux.jpg](https://user-images.githubusercontent.com/70181124/91111253-e6050d00-e634-11ea-9308-94279f82cabc.jpg)

The issues mentioned have been fixed. Thank you for your patience and feedback.
