### ISSUE TITLE
Always get 0 URLs found!

### ISSUE THREAD

**Issue by CooperTUGA** [VoldemortCommunity/ComboGen#9]
I always get 0 URLs found, I've seen people with the same problem, tried using a vpn but still get 0 URLs found, some of you know what happening and how can I solve it?

**Comment by lilcanopener1** [comment]
I been getting same problem with duck duck go we might not have the right
drivers installed idk

**Comment by Pra432** [comment]
yeah same problem 0 url are getting why

**Comment by saihiware** [comment]
O urls are found because you are not using good keywords.
Try using more effective keywords and increase the time too

**Comment by lilcanopener1** [comment]
Not true as it does it with keywords I know that work on the computer there
probably a capability error with the selected drivers he uses so please
know somthing 100% before you say something

**Comment by voldemort1912** [comment]
I would also like to add that repeated usage of the program ends up with Google banning your ip address thus keeping the program from scraping URLs. To get around this you must patiently wait for 20-45 minutes.
